#!/usr/bin/env bash
# Function to display information about a subdomain
display_info() {
    local domain=$1
    local subdomain=$2
    local record_type
    record_type=$(dig +short $subdomain.$domain | awk '{ if ($1 ~ /^[0-9.]*$/) print "A"; else print "CNAME"; }')
    local destination
    destination=$(dig +short $subdomain.$domain)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    local domain=$1
    local subdomain=$2

    # If only domain is provided, display information for default subdomains
    if [ -z "$subdomain" ]; then
        display_info $domain www
        display_info $domain lb-01
        display_info $domain web-01
        display_info $domain web-02
    else
        # Display information for the specified subdomain
        display_info $domain $subdomain
    fi
}
main $1 $2
