#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Configure Nginx
echo "Hello World!" > /var/www/html/index.html
# Restart Nginx (without using systemctl)
sudo service nginx start
