#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx
# Configure Nginx
echo "Holberton School" > /var/www/html/index.html
# Restart Nginx (without using systemctl)
service nginx start
