#!/usr/bin/env bash
# Install Nginx
sudo su
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
# Restart Nginx (without using systemctl)
service nginx start
