#!/usr/bin/env bash
sudo su
apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
# Define the redirection configuration
redirection_config="location /redirect_me {
    return 301 Moved Permanently https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Use sed to modify the default Nginx configuration file
sed -i '/server {/a \\n'"$redirection_config" /etc/nginx/sites-available/default
service nginx start
