#!/usr/bin/env bash
# Define the redirection configuration
TARGET_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Modify default server block configuration
sed -i 's/\/;/\n\tlocation \/redirect_me { return 301 '$TARGET_URL'; }\n;/' /etc/nginx/sites-available/default
service nginx start
