#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Configure Nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
# Perform a 301 Redirection
Target_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/server_name _;/$Target_string/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
Target_string_2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$Target_string_2/" /etc/nginx/sites-enabled/default
sudo service nginx restart
