#!/usr/bin/env bash
# MySQL commands to create replica_user and grant permissions
mysql -u root -p <<EOF
CREATE USER 'replica_user'@'%' IDENTIFIED BY 'replica1';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';
GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
EOF
