#!/usr/bin/env bash
# MySQL commands to create the user and grant permissions
mysql -u root -p <<EOF
CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
EOF