#!/usr/bin/env bash
# Update package lists and install MySQL 5.7.x
sudo apt update
sudo apt-key add signature.key
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C
echo "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7" | sudo tee -a /etc/apt/sources.list.d/mysql.list > /dev/null
sudo apt-get update
sudo apt install -f -y mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*

