#!/usr/bin/env bash
# Display a list of all running processes, including hierarchy and user-friendly format.
ps axo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --sort=-start | \
    awk 'NR==1 {print $0} NR>1 {printf("%-8s %-6s %-4s %-4s %-6s %-6s %-8s %-4s %-8s %-5s %s\n",$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)}'