#!/usr/bin/env bash
# Create PID file and handle signals as specified.
# Store PID in /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
trap 'cleanup' SIGQUIT SIGTERM
function cleanup() {
    rm -f /var/run/myscript.pid
    exit
}
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
