#!/usr/bin/env bash
# Stop the "4-to_infinity_and_beyond" process using kill.
# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")
# Check if the PID was found
if [[ -n $pid ]]; then
    # Send the SIGTERM signal to the process
    kill "$pid"
else
    echo "Process 4-to_infinity_and_beyond not found."
fi
