#!/usr/bin/env bash
# Initialize a counter
counter=1
# Use a while loop to display "Best School" 10 times

while [ $counter -le 10 ]
do
    # Check if it's the 9th iteration
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done