#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hour=0

while [ $hour -le 12 ]; do
    minute=1
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        printf "%d\n" $minute
        ((minute++))
    done
    ((hour++))
done