#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
service nginx stop
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/user\s*nginx;/user nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf
service nginx start
service nginx status
