#!/usr/bin/env bash
# Generate RSA key pair with specific requirements
# Check if the key already exists
#if [ -f ~/.ssh/school ]; then
#    echo "Key file ~/.ssh/school already exists."
#    exit 1
#fi
# Generate 4096-byte RSA key pair named school
ssh-keygen -t rsa -b 4096 -N 'betty' -f school
# echo "RSA key pair generated successfully."
